# Generated by Django 4.2.1 on 2023-06-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="citycode",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="countrycode",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="purpose",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
